### PR TITLE
Added a keyword `copling` in regards to issue 6#issuecomment-28867534…

### PR DESCRIPTION
**Pull request by yakir12**
…1. This allows the user to define what Gtk signal the Gtk widget and the Reactive Signal are connected with.

### CODE REVIEW

**Comment by timholy** [comment]
Thanks, @yakir12! Is your git knowledge good enough to know how to revise this a bit? Specifically, I'd ask:
- can you change the name `copling` to something like `gtksignal`? Or `gtksignalname`?
- can you add mention of the keyword to the documentation string?
- can you add a test?

If all this is too much, just let me know.

**Comment by yakir12** [comment]
I'll try! But the test is hard: it'll require manual editing of the text in the textbox to see if :changed works. Or can one emulate it programmatically?

**Comment by timholy** [comment]
Closed by #11.

**Comment by timholy** [comment]
You're right that a real test isn't easy. I might just run it and make sure it doesn't just error out, but we can do that later.

**Pull request closed without merging**
