### PR TITLE
Get most stuff working

### PR DESCRIPTION
**Pull request by timholy**

### CODE REVIEW

**Comment by timholy** [comment]
This is waiting on https://github.com/JuliaLang/METADATA.jl/pull/8408, perhaps among other things. But I'm about to start writing Documenter docs for it. I won't tackle the doc hosting until this moves to JuliaGizmos. @shashi, can I get the necessary privileges?

**Comment by shashi** [comment]
Invited. Go for it!

**Comment by timholy** [comment]
Great, thanks. I'm trying to add the requisite keys for hosting the docs (https://juliadocs.github.io/Documenter.jl/stable/man/hosting.html), but I notice that the "Settings" icon has now disappeared. If you'd like to set the keys up yourself, by all means, otherwise I think I will need more permissions.

**Comment by timholy** [comment]
CC @SimonDanisch in case this is useful for any of his ongoing "non-GL" backend work. The package is a fairly useful Reactive-based "frontend" for Gtk. See, for example, the `player` widget for implementing the more "scientific" control over slice-viewing. There's also a lot here on canvas interactions; I imagine that's less interesting, but at least it's worth knowing about.

You can build the docs locally by navigating to the `docs/` folder, saying `julia make.jl`, and then `firefox build/index.html`.

**Comment by shashi** [comment]
Sorry about that, I gave you the necessary privileges last night (if I got it right).

**Comment by timholy** [comment]
@shashi, looks like I don't have the permissions to turn on Codecov for JuliaGizmos, can you do that too?

**Comment by shashi** [comment]
Ah, I figured out the default access for org members is read-only. You should be able to do everything now. If not, let me know.

**Comment by timholy** [comment]
I think you'll probably get an email from codecov.io about allowing access to JuliaGizmos, presumably once you approve that I can do the rest. Thanks!

**Comment by shashi** [comment]
Done!

**Pull request merged**
