### PR TITLE
Travis - add osx, remove 0.7 add 1.1

### PR DESCRIPTION
**Pull request by ianshmean**
Attempting to root out https://github.com/JuliaImages/ImageView.jl/issues/175

### CODE REVIEW

**Comment by ianshmean** [comment]
Now that osx is added to travis, its seems like my issues from https://github.com/JuliaImages/ImageView.jl/issues/175 are replicated

**Comment by ianshmean** [comment]
These tests are failing: 
```julia
c = canvas(208, 207)
win = Window(c)
Gtk.showall(win)
sleep(0.1)
@test Graphics.width(c) == 208
@test Graphics.height(c) == 207
```
@timholy any ideas?!

**Comment by timholy** [comment]
Interesting, and obviously unfortunate. Is it "just" a test failure or does it fail in real-world practice? Do either of the following demos work for you:
- http://juliagraphics.github.io/Gtk.jl/latest/manual/canvas.html, which should give 
ss1
- https://github.com/JuliaGizmos/GtkReactive.jl/blob/master/examples/imageviewer.jl, which is basically documented [here](https://juliagizmos.github.io/GtkReactive.jl/latest/zoom_pan.html)

**Comment by ianshmean** [comment]
Both examples result in blank windows, with no errors. 
Screen Shot 2019-05-01 at 11 08 24 PM

It would be good if another MacOS user could locally test this, and if theirs works, figure out what's different about my setup

**Comment by timholy** [comment]
OK, this is probably a Gtk or Cairo error. Do any non-canvas aspects of Gtk work for you?

**Comment by ianshmean** [comment]
Cairo seems ok.. tests pass and this renders the png properly
https://github.com/JuliaGraphics/Cairo.jl/blob/master/samples/sample_arc.jl

Gtk tests pass, but the windows during the tests are blank, as is the window in the basic examples
http://juliagraphics.github.io/Gtk.jl/latest/manual/gettingStarted.html

I just removed the full Gtk package dir and rebuilt and have the same issue

**Comment by timholy** [comment]
OK, it seems this is a Gtk issue. I'll close this and the one in ImageView, and perhaps you can report issues there.

This adds fuel to the fire of replacing Gtk with something else. But that is a lot of work so I am not there yet.

**Comment by ianshmean** [comment]
Ok. I've repurposed https://github.com/JuliaGraphics/Gtk.jl/issues/414

Is this PR worth merging? Only adjust travis to cover osx and v1.1

**Comment by timholy** [comment]
Indeed. Letting osx fail will remind me that we need to fix this sometime. Thanks!

**Comment by timholy** [comment]
Ah shoot, I should have asked you to change the bounds in Project.toml (principle: don't claim to support 0.7 unless you're testing it). But I will fix it.

**Comment by ianshmean** [comment]
Ah, missed that. Apologies

**Pull request merged**
